### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#101]
We got some feedback from folks this weekend.

Here are the issues. 

From Melissa iOS (two emails)
"I have some feedback to provide about my application using experience:

At 120 on Sunday, showing no trolleys being tracked."

and

"I have some feedback to provide about my application using experience:

It appears trolley 2 has been stopped at heritage green for an hour. Not sure if it is broken down or a glitch in the tracking."

And one from Will (iOS) 
"I have some feedback to provide about my application using experience:

Standing at river and main/Augusta and watching the icons move and trolley has not passed us. "

**Comment by bikeoid** [comment]
Re "Standing at river and main/Augusta and watching the icons move and trolley has not passed us"

The ghostly trolley icon passing by might be similar to the the hyperspeed we've seen at startup.    I have managed to reproduce the condition locally with the following steps:

 * Beacon running
 * Enable a firewall to the server. 
 * Now the Beacon "Log" screen stops updating, but the GPS continues to acquire data at the previous rate.   Server requests take one to several minutes to time out because of the firewall.   This is the same condition as would be seen locally if the mobile Internet connection was not working.
 * Open the firewall.
 * All the queued location requests suddenly come through at once.   Locally, each request completes in about 150 mSec.   This can be seen in the time stamps on the screen capture.

The good news is that now it should be possible to fix this by detecting and avoid queued reports

.   The bad news is that it means that the mobile Internet connection is not as reliable as it should be.

![screenshot_2015-10-27-21-37-05](https://cloud.githubusercontent.com/assets/75929/10777446/f8c92112-7cf1-11e5-9aff-2a317018aad9.png)

**Comment by bikeoid** [comment]
I got a chance to see one of the problems on the trolley that is running (the other driver had a family emergency, and it's not running tonight).

I watched it as it started OK in the Greenlink lot, but by some point during the first route pass it had stopped transmitting.    I jumped on at the County Square parking lot and we looked at it.   It took a bit of fiddling because I don't know which are the home / back functions on that tablet.  By the time we got the trolley app up, it was streaming numbers very quickly on the log screen,  then quickly slowed to normal speed.   They were all in the coordinates of the County Square, so I'm not sure if it was Hiper-speed in the app or not.   It appeared that our activity had unfrozen something - but it's not clear whether it was the Internet connectivity that was unfrozen or some app function.  This was on Trolley 6 which we had cleared out all previously memorized WiFi hotspots.

 *  I didn't check the Internet/Wifi first to confirm that it was already working, but my feeling is that it's not likely that our tablet functions could have caused the Internet connection to awaken.  The Internet was working well by the time I checked.
 * John (the driver) will run a test tomorrow during LunchLink in which he turns on the tablet only, but not bring up the icon.   If someone later tells him to check the tablet, he'll bring up the Trolley from the shortcut and see if that is enough to correct the problem.
 *  Previously after being asked to check the tablet, John has brought up the program via the Trolley icon and that has corrected the problem.

**Comment by bikeoid** [comment]
During lunchlink, the system worked with no glitches.   So with the same driver turning it on but getting different results, there is an inconsistency somewhere.

The pursuit of a mobile device with integrated Internet with self-startup appears to be our best bet now for a reliable solution.

**Comment by ajhodges** [comment]
:clap:
