### ISSUE TITLE
A Trolley of Constant Tracking

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#114]
On the Thursday (12/3) run, the tracker for trolley 6 stayed on and running throughout the night. Here's @ajhodges comment from the New Device thread https://github.com/codeforgreenville/trolley-tracker/issues/105#issuecomment-161866050

**Comment by tkenney-gvl** [comment]
Since this is the same issue as #114, I'm posting it here, even though this started in #115. 
Ok, so after the trolley ended its run for the day it still showed online. Grant went over there to check it out and found the phone on, but the charging indicator was showing that the phone was running on battery. We tested a lot of things, going through having it completely off (manually) and cranking the trolley, which resulted in the phone turning on. After the boot, we turned the trolley off, but the phone stayed on. He took it out of the cradle so it wouldn't have anything connected to it and it was still on. I had him double-check the trolley app settings, and both checkboxes were checked (background testing and auto-off). We did run into some phone glitches where the phone rebooted 2 times after we cranked the trolley and then before the Nexus was fully booted turned the trolley back off again, but other than that, the power stuff seems to be working as expected with exception of it not wanting to turn off when no power is supplied. I'm not sure if you can get debug info from the Tracker app itself, but it looks like it's either not executing the reboot -p option or something in the system is overriding it (for that phone). We'll have to see about number 6 tonight and see if we have something similar.

**Comment by ajhodges** [comment]
Hmmm that's no good. I'll have to do some more testing with the auto-off feature to see what's up. Not able to debug this remotely unfortunately. Thanks for the report and the leg work!

**Comment by bikeoid** [comment]
The trolley with the phone in the roof (6) has a promising look.   I'm going to wait until they run the same route , preferably on the same day before a final conclusion.    Here's hoping to out of sight, out of mind mounting!

Regarding this issue: there was a single glitch at 6:00 as it started the run that I couldn't explain - it came online at the trolley barn, there was a data gap, then it showed up at University square parking, then one data point at the University Ridge-Church St intersection, then it finally picked up normal operation for the rest of the night after the Church St bridge: gaps of about 2-3 minutes each.    Some extra reboots could explain this, or problems starting to acquire the GPS (which it doesn't seem like).

**Comment by ajhodges** [comment]
I'm going to push an update that changes my shutdown method from a 'hard shutdown' (handled by the kernel, immediate) to a 'soft shutdown' (handled by Android, probably cleaner). Maybe this will help with the glitches? Not sure what else to try. I also added a toast notification that should pop up every time the power is unplugged (right before the shutdown) to help with debugging.

**Comment by ajhodges** [comment]
(Wrote this right after the last comment and never submitted it)
Had some more issues I needed to fix with the auto-off feature. Pushing another update. It's possible that the phones will need to be rebooted after updating and might need root access granted again. Found a bug that might have been causing your rebooting issue. I have noticed that sometimes the 'power disconnected' event takes a long time (up to 1 min) to be picked up by my code - nothing I can really do about that. Hopefully it doesn't hang indefinitely though.

**Comment by bikeoid** [comment]
Both trolleys were running today when I was downtown - both checked in between 10:30 and 11:00 but both then went offline by 11:00.

I'm not sure which version they have now, but is there any harm in letting the Android power management shut them down when ignition power is removed?    It creates an unnecessary battery cycle, but I don't know the other implications.

**Comment by ajhodges** [comment]
There probably isn't any harm in it, but it's possible that it could
trigger a power saving mode which could limit the GPS and/or connectivity
when it boots back up. The other thing I'd be worried about is if the
auto-on would be affected if the battery was totally dead. But it is an
option if we test it.

I guess our first troubleshooting step might be to make sure the agent is
updated (then reboot) and then turn off WiFi on the nexuses. I am still
confused by this superspeed behavior, I was positive that we wouldn't see
that again! I will look in to timeout theory we had before.

**Comment by ajhodges** [comment]
Just pushed another update. The auto-off feature should work about as well as it possibly can now. Also should have the fix for our superspeed issues and maybe some connectivity issues.

**Comment by agautsc** [comment]
Closing thanks to @ajhodges most recent updates :clap:
