### ISSUE TITLE
Testing for the weekend starting Thursday December 10th

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#116]
Would folks be up for meeting on Thursday evening and get on the trolleys and see if we can't debug any issues we're having? @bikeoid @ajhodges ?

**Comment by bikeoid** [comment]
I'm all for the concept to be able to nail this down.    The latest software *may* have solved all the problems, but it's good to verify.

Troubleshooting a live unit is difficult even with the console-mounted unit because it can only be safely manipulated while stopped and needing to reach across the driver to look at any screens.

An alternative would be to take 2 hours in the trolley lot: since most problems seemed to happen early in the run, try various combinations lengths of on and off times to confirm that it continues to work as expected.

**Comment by agautsc** [comment]
I think we need some IRL driving around. @greenlinktransit do you think it could be possible for us to show up at the start of the route (something like 545pm) see how the trolley starts up and see if there is something we can debug before it starts. Then ride around with them for a loop or two and see if things stay connected.

**Comment by ajhodges** [comment]
I won't be able to make it any earlier than 6 but I can intercept your trolley. Just make sure the tracker agents are updated if you are able to get on the trolleys before the route starts.

**Comment by greenlinktransit** [comment]
@agautsc @ajhodges @bikeoid Guys, I agree that we need to do some stationary and mobile troubleshooting but unfortunately I cannot do it tomorrow or this weekend (although, I can do it during Lunchlink).  My parents are in town and they have a lineup of activities scheduled.  I'd be more than happy to give you guys access to the trolleys as much as you need next week if you can wait.

Alternatively, I don't see any issues with you guys jumping on the trolleys yourselves. @mblizzard-gvl or @tkenney-gvl might be able to join you if they are available. Just let me know what you decide to do so I can give my folks a heads up.

**Comment by jeremywight** [comment]
I've got a meeting tomorrow evening so won't be able to make it, but I
think it's a great idea @agautsch

**Comment by agautsc** [comment]
@greenlinktransit 

If the drivers don't mind, my preference would be to come out tomorrow around 545pm, watch the trolleys fire up, see if there is anything we can do make sure they get online, update any apps that need to be updated and then drive around on the trolley for a while.

**Comment by greenlinktransit** [comment]
@agautsc That shouldn't be a problem.  I'll have Steve tell the drivers that you'll be there.

**Comment by agautsc** [comment]
@bikeoid and I are on trolley 5 right now. We updated the agent software and restarted the phone. The phone on trolley 5 was turned on earlier today and the battery is low, but it's plugged in and charging. More to come...

**Comment by agautsc** [comment]
Went ahead and turned WiFi completely of on 5.

**Comment by agautsc** [comment]
Got on 6. The phone is on the dash. The app was already up-to-date. I went ahead and turned off the WiFi on this one too.

**Comment by ajhodges** [comment]
Just about killed myself trying to catch trolley 5. Going to say the ETA
feature would be one of my top priorities once we get the reliability
ironed out

**Comment by agautsc** [comment]
They have both been running all night so far. A couple notes:
* Both drivers were super nice and helpful.
* The Well route goes down Church and loops around.
* We think both trolleys still have their WiFi on. The hardware is still there for sure.
* Both phones are mounted on the dash.
* Both phones are up-to-date on agent software and WiFi is shut off. There was a bunch of other phone updates pending. I didn't update those. Didn't want to kill the data limits.

**Comment by agautsc** [comment]
Oh, one last note, we need to start a CfG Health Club. Hodges did almost die running to the trolley.

**Comment by jeremywight** [comment]
hahaha :)

**Comment by ajhodges** [comment]
Yuk it up guys. Us programmers don't use our legs very often. ;p

Excited to see that both trolleys are still going strong! Hopefully they
both shut off without any issue tonight. Here's hoping for a good weekend.

**Comment by ajhodges** [comment]
So the trolleys have been in the bay for a while now (>20min) and they're both still reporting location. This could mean one of three things
1. The trolleys are still actually on and running
2. The keys are still in the trolley's ignition
3. My shutoff thing still doesn't work.

Not ruling out 3 as a possibility, but I think 2 is very likely. I could see them not bothering to remove the keys in the maintenance bay.

Since it doesn't seem to matter if the device battery dies (and trying to make sure the key always gets removed from the ignition leaves us open to human error), maybe we should do some geofencing in the backend and ignore all location updates from the Greenlink station? Or we could also try logic to say if a trolley hasn't moved > 10m in 20 minutes, mark it as inactive.

**Comment by greenlinktransit** [comment]
@ajhodges did you ever see when the devices powered off?  When I tested them last week I noticed that no power was being sent to the Nexus' when the keys were just in the ignition.  The trolley had to be ignited and running for them to receive power.

If your shutoff mechanism is working, I'd bet on the problem being #1. We typically wash the vehicles inside & out once they finish their runs, so it sometimes takes 20+ mins for the vehicles to go out of their idle state once they pull into our Maintenance Facility.  I've never seen our drivers leave the keys in the ignition when the vehicle is off, but I guess it's possible.  Usually they drop them on the dash.

**Comment by mblizzard-gvl** [comment]
@agautsc I was curious if the WIFI was causing trouble. The phones have unlimited data plans so it would not matter if you want to apply the phone updates. From our perspective, it would be fine to leave the WIFI off.

It sounds like there was not an issue with the phone being mounted overhead.  Should we mount both overhead or is it too soon to tell?  Either @greenlinktransit, @tkenney-gvl  or myself could would with the shop to have it mounted overhead if you feel it is time. 

I've been thinking about this some.  Does it matter if the phone shuts down or not?  If you are able to set the Trolley to an inactive state then the phone will just eventually die.  Once the bus is powered up it will start charging and boot up anyway so does it really matter that the phone is powered off by the app?

**Comment by ajhodges** [comment]
@greenlinktransit I might have spoken too soon, then. Could have been just left running. It's hard for me to see exactly when the trolleys turned off for the night (@bikeoid any chance we could generate a timeseries graph or something?) but I did see them both get started this morning. So maybe the auto-off feature is working after all. I thought I noticed the power still being on when we turned off the trolley, but if that's what you saw then I'm sure I was just jumping to conclusions.

I think we will know more after a few more days. @mblizzard-gvl we should probably wait to see if we make it through the weekend without any issues. Maybe emphasize to the drivers that they definitely cannot unplug them. Then after we have a baseline of sorts, we should mount one of them in the overhead compartment (@agautsc said neither of them currently are) and see what the impact is.

And yeah, I don't think it matters terribly if the phone shuts down, so long is it's not actually pulling power from the trolley battery. We should try to put some logic in so that trolleys don't show up while they're being washed/etc anyways.

**Comment by agautsc** [comment]
I'm not sure if the WiFi was causing trouble on the phones or not. I do know that @bikeoid was having trouble. His phone was connecting to the WiFi and running slower or not at all. It seemed best to just keep the phones WiFi off. If the data is unlimited then I say we just switch the Play Store settings to "Auto-update apps at any time." That will make apps update over cell networks.

I think it's safer to keep the WiFi. Things seemed to work great last night. Let's cross our fingers for today during lunch and the rest of the weekend.

**Comment by ajhodges** [comment]
I've seen the trolleys turn on and off multiple times in the greenlink
parking lot this morning, which I think is a good sign!

**Comment by bikeoid** [comment]
Re: WiFi - I wouldn't expect it to cause problems if it's just the city Wifi at a single location such as the trolley yard.   The problems I saw were because I had set my phone to remember the WiFi networks in the roof of the trolleys.   I ran into problems while in the first unit, and also when we met the second unit at University Square.   After I told it to 'forget' the networks, there was no problem.

Re: showing when stopped - I would propose removing them if they haven't moved more than X meters in 10 minutes.   The last update time will still be available for our purposes on the t, but will be removed from the active list.   I'm a bit hesitant about Geofencing, because it's still useful to see the Trolley location during a driver's scheduled break.

**Comment by agautsc** [comment]
My only thought on don't show after 'x' time is that the trolleys do tend to idle while waiting for folks. For example, last night trolley 6 waited at County Square for over half an hour while waiting on folks to jump on the trolley to ride to the Well. Let's hold off on any new features on that front. It seems like the updates Hodges made might be working.

**Comment by bikeoid** [comment]
Friday's Lunchlink started by itself.   I'm now confident enough to turn on the paging system to catch if it goes out for the rest of the weekend.

**Comment by greenlinktransit** [comment]
I ate lunch on Main Street today and the Tracker was working to perfection!

**Comment by agautsc** [comment]
I went ahead and changed the title of this issue to be an open thread for testing for the entire weekend.

So far, Thursday night and Friday lunch have been great. :clap:

**Comment by ajhodges** [comment]
48 hours of continuous trolley tracking action! I can dig it.

**Comment by agautsc** [comment]
![bitmoji-20151212082843](https://cloud.githubusercontent.com/assets/1761333/11764864/12457d20-a10f-11e5-98e3-88a7f5d38d34.png)

**Comment by bikeoid** [comment]
Flawless operation for the weekend!  I make the motion to move out of beta stage and to unleash the publicity machine!   Great job on the set of fixes @ajhodges , and great idea about the hands-on ride along @agautsc  to confirm all operating parameters.

**Comment by ajhodges** [comment]
I can't take the credit. I am pretty sure the new devices are making a big
difference! And I'm pretty sure things would still be broken if yall didn't
update the app and turn off the WiFi.

I'd like to finish the UI in the Android client before we push it live. Are
there any other things we need to consider? Is the web server we are using
beefy enough to handle >100 users simultaneously polling the trolley
location? Are we sure mounting the device overhead won't affect signal? Who
is going to maintain the schedule? Did we come to a conclusion on the idle
trolley issue?

Maybe we should have one last meetup before we pull the trigger. As a
celebration if nothing else!

**Comment by bikeoid** [comment]
The web server is well oversized in both hardware and bandwidth.  

Re: overhead mounting - that will need a test first on one machine.  Even if we're live, it could be done on a Thursday night so that it could be reverted on Friday if it doesn't work.   If the current mounting is sufficiently theft resistant, it could remain where it is.

I'm doing the schedule until I finish the route editor, after which time Greenlink will keep it current.

Re: idle trolley - I'd rather this be an issue driven by end user needs: they're not likely to be confused by a trolley that pops up when there are no routes, and it would be useful to know that the shuttle is waiting in some location even if it isn't moving.

**Comment by agautsc** [comment]
Happily closing after 100% Uptime Weekend.
