### ISSUE TITLE
Feedback from Lori Hartman

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#122]
Hi TrolleyTracker,
I have some feedback to provide about my application using experience: Your map is wrong we The Trolley's do not go down University St at all to the round about. That area is too dangerous for the trolley. We make our left on Bradshaw, left on Howe, then a right into University Ridge.

@greenlinktransit is this a driver?

**Comment by greenlinktransit** [comment]
@agautsc Yep, that's one of our drivers.  She's right....the trolleys do not serve University Street, however, I do not recall them being on the Trolley Tracker map.  @bikeoid could you confirm?

**Comment by bikeoid** [comment]
University St is currently on the map, but only because a few drivers went that way during the day when I was first recording it on GPS.

I was planning to revise it to eliminate that street anyway, since the route needs to go past the new trolley Park & Ride lot in order to pick up that stop when it opens.

**Comment by bikeoid** [comment]
Updated routes to turn down Bradshaw instead of University
