### ISSUE TITLE
Agenda: May 17th

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#143]
- 5:30pm to 6pm - Sit and Meet Pennyroyal Tea
- 6pm - Marketing ideas for trolley tracker - See: https://github.com/codeforgreenville/trolley-tracker/issues/137#issuecomment-219049098 
- @ajhodges made a bunch of updates to the Android app. We can get an update to that. 
- @allella Catches up on the API
- Discussion on designer reach out. I got some thoughts on that idear. 
- ...

Please add / edit where you see fit. 
![bitmoji](https://render.bitstrips.com/v2/cpanel/8968004-125161747_3-s4-v1.png?palette=1&width=246)

**Comment by ajhodges** [comment]
I hate to thin the ranks even more, but there's a 50% chance I won't be able to make it tomorrow. So here's my update:

Pushed a new release Saturday night. Fixes the 'show my location' feature which was broken in Android Marshmallow+ due to the use of a deprecated API, attempts to fix a couple bugs when the API returns no data, adds the 'swipe to refresh' gesture to the schedule page, and added route previews (click on an item in the schedule). Would love any/all feedback on this release. Should be pretty solid, except for one little bug where the window title doesn't get updated correctly after a screen rotate (pretty obscure bug).

Here are the updated metrics (will update this tomorrow to see how Artisphere affected downloads):
![image](https://cloud.githubusercontent.com/assets/856738/15291592/bafb6666-1b4c-11e6-8582-006634792f7f.png)

And since the topic is marketing, here is some of the data on an AdWords campaign that I'm running that I don't think I've mentioned before:
![image](https://cloud.githubusercontent.com/assets/856738/15291699/439c64e8-1b4d-11e6-814a-866ebac740f6.png)

I believe I am currently targeting the ad to people searching for Greenville within a 20 mile radius of Greenville. It's not getting too many hits, but when it does, people seem to click on it, and when they click on it there's a pretty good chance of them downloading the app.

**Comment by ajhodges** [comment]
Had a bug pop up in my last update where the app wouldn't load on older devices. Thankfully we got an e-mail about it and I was able to fix it quickly.

![image](https://cloud.githubusercontent.com/assets/856738/15323677/3c16f958-1c11-11e6-9775-298385ea17e4.png)

Here's the updated stats for the weekend. Looks like a little boost from artisphere, but not as much as I thought.

**Comment by jeremywight** [comment]
Wow great stuff, both Adam's! (Apparently we just need more Adam's in the
crew :) )

**Comment by allella** [comment]
I believe Pam Wood Browne is attending. She is starting up SC Code in August and may want to share ideas about having students partner on CFG projects.

**Comment by agautsc** [comment]
Meeting notes:
- Hack night to work on wait time estimates, hotel and attractions layer @bikeoid could you meet next Tuesday for a hack night?
- Jim's API focus is going beyond meetups and now there is https://data.openupstate.org/
- Marketing of sticker and clings talking to Greenlink about funding. @rhynodesigns offered to talk to the hotels. @agautsc offered to reach out to Greenville Drive again.

**Comment by bikeoid** [comment]
As of right now, it appears that I can make next Tuesday's hack night.

The lack of a geek event calendar was noted in tonight's .NET meeting, so I posted Jim's API link!

**Comment by rhynodesigns** [comment]
Mast General Store was closed, but their window was totally clean, no ads or brochures.

I went and spoke with Brandon at the Hyatt and they will not have any sort of stand or anything visible. I asked if he had heard of the trolley tracker app, he said no. He said most people think they provide transportation, but they hand out physical trolley maps, but are currently out of them.

I'm not sure we want to get into the 'making/distributing flyers' business. I think getting the workers there to suggest the trolley tracker would be simply a matter of request/training. Show them the app, and ask them to share with fellow workers.

I don't know what a conversation with someone higher up would be like, suggesting they hang a tv with the trolley tracking app on it...with restaurants and points of interest...

**Comment by jeremywight** [comment]
I actually removed the Hack Night next week both from Meetup.com and from
the OpenWorks calendar. If you guys are going to meet at OpenWorks I can
put it back on there though. Just let me know. (I cancelled because I will
be out of town and I didn't want to ask @agautsc to lead two weeks in a row)
