### ISSUE TITLE
Getting the Beacons up and running

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#45]
My hope is to be able to go back to Greenlink this week and get the beacon app up and running this week. @dacohenii @Linktheoriginal Would it be possible to get the web app tied in to the beacon so we can test this bad boy on a live site?

-Adam

**Comment by Linktheoriginal** [comment]
It's currently driven off the new .NET API.  Anything that's being pushed in there will show on the app.  The only thing not driven off the API is the route information + showing the active route path.

http://linktheorigi.webfactional.com/trolley/

**Comment by agautsc** [comment]
@ajhodges @bikeoid Is this something y'all can tie in to the API?

**Comment by bikeoid** [comment]
The API should be ready to go - I'm not familiar with the platform(s) in the example web app; I tend to do this type of interface in raw Javascript interacting with Leaflet.

  I noticed that there is an offset to the route schedule - I think the current server is in another time zone, so it might return routes that are off by several hours.    The 'Active routes' query works though.  Even if the routes are off, the trolley beacons should work.

   The new server is being set up by WallingIS.com  - when it's ready, the URL and login credentials will change.    I will refrain from making changes to that server so that the beacon will operate as soon as Verizon wakes from their long winter nap.

**Comment by dacohenii** [comment]
I talked to a guy the other day who says he helped install the wifi access
points on all greenlink buses, but greenlink experienced overages $1000+
more per month than expected. However, he says that not only did Greenlink
shut off the units, but they also removed their antennas. I wonder if this
is part of the reason they're taking so long to get it working.

As far as the web app is concerned, it's leaflet+ jQuery with a Django
backend that calls the API. We could potentially serve the files statically
on the same domain and call the API directly.

**Comment by bikeoid** [comment]
The new server is up, and I've pointed the simulated beacon for Trolley 999 away from the old server to the new server  at http://tracker.wallinginfosystems.com/   (DB Visualizer doesn't work on the new server at the moment).

**Comment by ajhodges** [comment]
@agautsc and I just set up both trolleys with the beacon app and their internet seems to be working. The lunch trolley service starts in a little over an hour so I guess we'll have our moment of truth!!! Trolleys are numbered 5 and 6 BTW (which conveniently corresponds to the last digit of their respective license plates).
