### ISSUE TITLE
Reopening the Idea of Providing the Devices

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#61]
Since we haven't been able to get the internet and the tablets on the trolleys running on any consistent basis I think it's worth considering going back to bringing our own devices to the trolley.

The easiest way could do this without having them run new wires might be getting some type of MicroUSB splitter and have them still charge their tablets and also charge a phone. We probably could mount that phone on the backside of the tablet mount.

That's my bright idea. Other bright ideas are welcomed.

**Comment by ajhodges** [comment]
I think one of the biggest issues seems to be the trolley drivers unplugging the tablets to charge their own phones. We were kind of given warning about this if I remember correctly. So using a MicroUSB splitter and our own device seems susceptible to the same problems. Not to mention then we're totally SOL if the device gets stolen (someone mentioned that trolleys have also been broken in to and had their tablets stolen out of them before). And the other cons of the initial device investment/monthly data fees.

How about some sort of "lock" for the USB cable? Similar to what you see on the mounts at the Verizon/AT&T/T-Mobile store or best buy, where the devices are plugged in and relatively tamper proof. That seems like a more direct solution to the issue.

I've looked online for such a thing and I am coming up empty. But even just epoxy/solder/possibly zip ties could prevent the driver from using our power.

The WiFi is a different issue, I suppose. But I feel like that is also something we should be able to solve.

**Comment by bikeoid** [comment]
We may end up needing to secure the tablet connection, but if the root cause is that the drivers need a place to charge their phone, what about providing them with USB socket(s)?  Such as if there is a "cigarette lighter socket", give them dual USB plugins.   It will be more challenging to do that without a lighter socket.

**Comment by ajhodges** [comment]
Turning the phone on and off automatically as @bikeoid suggested in another issue is more difficult than we had originally thought because the tablets *always* have power. I'm not sure if Rick intentionally wired it that way or not (or if there is even another way to wire it on the trolley), but the tablets are essentially wired directly to the battery. From my own limited car audio installation experience, you should be able to get a signal from the ignition and have a switched power source. That would solve his trolley battery drain issue and help us start/stop the tablets automatically (which is definitely possible with some hackery). But I have a strong feeling he is not going to want to deal with that.

**Comment by ajhodges** [comment]
Providing them with USB sockets could work, but I think it would have to be something like a little USB hub glued to the dash, because I don't think there is much room to add any more ports. That is something we would have to talk to Rick about as well I guess.
