### ISSUE TITLE
Thread for Friday night testing

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker#69]
6pm they are both showing up https://goo.gl/photos/GthYyafqKfm7M7Kg9

**Comment by austin9350** [comment]
Looking good on my end

![img_1828](https://cloud.githubusercontent.com/assets/2276307/9696347/52930990-533c-11e5-86e8-c6cc7b2f92e4.jpg)

**Comment by ajhodges** [comment]
Guess they left the tablets on after their shift was over. Wonder if they'll be able to start the trolleys tomorrow morning? :p

**Comment by agautsc** [comment]
I lost power last night around 830pm and so wasn't checking after that. Did both trolleys stay online all night?

**Comment by ajhodges** [comment]
Yep they were still going at midnight, I think. I'm not sure if they use enough power to drain the trolley's battery

**Comment by jeremywight** [comment]
Greetings from Saigon... Awesome stuff! Would it be possible to detect if
the same coordinates were being passed for xx minutes and then show that
trolley as offline until the coordinates changed again?

**Comment by bikeoid** [comment]
If we do this, we'll need to set something larger than 7 minutes - drivers routinely take a break at the Greenlink facility for 5 minutes, and it takes 7 minutes to do a wheelchair pickup or dropoff.     And we need to make it easy for our own purposes to show that the beacon is still transmitting (perhaps on the DB display).

We can easily add the time the last beacon was received, and seconds since received (since clients' time reference could be a different time zone or just not set correctly).   I believe this is not needed in the core "Running Trolleys" API call though.   

Thoughts?
